version: "3.8"

services:
  checkmk:
    image: checkmk/check-mk-community:2.5.0p2
    container_name: monitoring
    restart: always
    ports:
      - "8080:5000"
      - "8000:8000"
    tmpfs:
      - /opt/omd/sites/cmk/tmp:uid=1000,gid=1000
    volumes:
      - monitoring:/omd/sites
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - app_network

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: appdb
      MYSQL_USER: cmk
      MYSQL_PASSWORD: cmkpass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -uroot -p$$MYSQL_ROOT_PASSWORD --silent"]
      interval: 10s
      timeout: 5s
      retries: 12
      start_period: 25s
    networks:
      - app_network

  mysql_mirror:
    image: mysql:8.0
    container_name: mysql_mirror
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: appdb   
      MYSQL_USER: cmk          
      MYSQL_PASSWORD: cmkpass   
    volumes:
      - mysql_mirror_data:/var/lib/mysql 
      - ./db/init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -uroot -p$$MYSQL_ROOT_PASSWORD --silent"]
      interval: 10s
      timeout: 5s
      retries: 12
      start_period: 25s
    networks:
      - app_network

  passbolt_db:
    image: mariadb:10.11
    container_name: passbolt_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: passbolt
      MYSQL_USER: passbolt
      MYSQL_PASSWORD: passboltpass
    volumes:
      - passbolt_data:/var/lib/mysql
    networks:
      - app_network

  passbolt:
    image: passbolt/passbolt:latest-ce
    container_name: passbolt_app
    restart: always
    depends_on:
      - passbolt_db
    ports:
      - "9797:80"
    environment:
      APP_FULL_BASE_URL: http://localhost:9797
      DATASOURCES_DEFAULT_HOST: passbolt_db
      DATASOURCES_DEFAULT_USERNAME: passbolt
      DATASOURCES_DEFAULT_PASSWORD: passboltpass
      DATASOURCES_DEFAULT_DATABASE: passbolt
      DATASOURCES_DEFAULT_DRIVER: 'Cake\Database\Driver\Mysql'
    networks:
      - app_network

  backend:
    build: ./backend
    container_name: backend
    restart: always
    ports:
      - "3000:3000"
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - NODE_ENV=production
      - PORT=3000
    networks:
      - app_network
    depends_on:
      mysql:
        condition: service_healthy
      mysql_mirror:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      target: dev
    container_name: frontend
    restart: always
    command: npm run dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      - HOST=0.0.0.0
    networks:
      - app_network
    depends_on:
      - backend

volumes:
  monitoring:
  mysql_data:
  passbolt_data:
  mysql_mirror_data:

networks:
  app_network: