CREATE TABLE IF NOT EXISTS registros (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    fecha TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    dato LONGTEXT NOT NULL,
    PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS historial_estados (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    fecha TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    contenedor VARCHAR(255) NOT NULL,
    activo TINYINT(1) NOT NULL,
    PRIMARY KEY (id),
    KEY idx_historial_contenedor_fecha (contenedor, fecha)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
